# Generated by Django 5.2.12 on 2026-03-22 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vortex Forge', max_length=120)),
                ('company_name', models.CharField(default='Vortex Forge S.r.l.', max_length=160)),
                ('support_email', models.EmailField(default='support@vortexforge.local', max_length=254)),
                ('support_phone', models.CharField(default='+39 351 984 4148', max_length=40)),
                ('company_address', models.CharField(default='Via Magellano 27, Busa di Vigonza, Padova, Veneto, Italia', max_length=255)),
                ('vat_number', models.CharField(default='P. IVA da inserire', max_length=40)),
                ('hero_title', models.CharField(default='Gaming PC, configurazioni custom e supporto professionale.', max_length=180)),
                ('hero_subtitle', models.TextField(default='Una piattaforma professionale per presentare build curate, raccogliere richieste personalizzate e gestire tutto da un pannello amministrativo reale.')),
                ('trust_note', models.CharField(default='Sito protetto, assistenza dedicata, richieste tracciate e gestione sicura account.', max_length=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazione sito',
                'verbose_name_plural': 'Impostazioni sito',
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log amministrativo',
                'verbose_name_plural': 'Log amministrativi',
                'ordering': ['-created_at'],
            },
        ),
    ]
