# Generated by Django 5.2.12 on 2026-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='trust_note_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='PC gaming, configurazioni custom e supporto professionale.', max_length=180),
        ),
    ]
