# Generated by Django 5.2.12 on 2026-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_hero_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='PC per gaming, editing, rendering e workstation.', max_length=180),
        ),
    ]
