# Generated by Django 5.2.12 on 2026-03-22 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('components', models.TextField(help_text='Una componente per riga')),
                ('category', models.CharField(max_length=120)),
                ('primary_image', models.ImageField(upload_to='builds/primary/')),
                ('availability_status', models.CharField(choices=[('available', 'Disponibile'), ('preorder', 'Preordine'), ('unavailable', 'Non disponibile')], default='available', max_length=20)),
                ('highlight_badge', models.CharField(choices=[('none', 'Nessuna'), ('recommended', 'Consigliata'), ('on_sale', 'In offerta'), ('best_seller', 'Piu venduta')], default='none', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builds', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Build',
                'ordering': ['sort_order', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builds/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.build')),
            ],
            options={
                'verbose_name': 'Immagine build',
                'verbose_name_plural': 'Immagini build',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuildPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nuova'), ('in_progress', 'In gestione'), ('ready', 'Pronta'), ('closed', 'Chiusa')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='catalog.build')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta acquisto build',
                'verbose_name_plural': 'Richieste acquisto build',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomBuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=120)),
                ('gpu', models.CharField(max_length=120)),
                ('ram', models.CharField(max_length=120)),
                ('storage', models.CharField(max_length=120)),
                ('cooling', models.CharField(max_length=120)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Inviata'), ('in_review', 'In revisione'), ('quoted', 'Preventivo inviato'), ('closed', 'Chiusa')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_build_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta build personalizzata',
                'verbose_name_plural': 'Richieste build personalizzate',
                'ordering': ['-created_at'],
            },
        ),
    ]
