# Generated by Django 5.2.12 on 2026-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='category_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='build',
            name='components_en',
            field=models.TextField(blank=True, help_text='Una componente per riga in inglese'),
        ),
        migrations.AddField(
            model_name='build',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='build',
            name='name_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='build',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
