# Generated by Django 5.2.12 on 2026-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_build_category_en_build_components_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuildrequest',
            name='case',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='extra_fans',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='motherboard',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='network_card',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='power_supply',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
