# Generated by Codex on 2026-03-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_custom_request_statuses(apps, schema_editor):
    CustomBuildRequest = apps.get_model("catalog", "CustomBuildRequest")
    for item in CustomBuildRequest.objects.all():
        if item.status == "closed":
            item.status = "cancelled"
        else:
            item.status = "in_approval"
        if not getattr(item, "currency", ""):
            item.currency = "EUR"
        item.save(update_fields=["status", "currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_custombuildrequest_case_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="custombuildrequest",
            old_name="budget",
            new_name="budget_max",
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="approved_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="budget_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custombuildrequest",
            name="reviewed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_custom_requests", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="cooling",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="cpu",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="gpu",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="ram",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="status",
            field=models.CharField(choices=[("in_approval", "In fase di approvazione"), ("approved", "Approvata"), ("payment_pending", "Pagamento in attesa"), ("paid", "Pagata"), ("payment_failed", "Pagamento fallito"), ("rejected", "Rifiutata"), ("cancelled", "Annullata")], default="in_approval", max_length=20),
        ),
        migrations.AlterField(
            model_name="custombuildrequest",
            name="storage",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(migrate_custom_request_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name="CustomBuildPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("provider", models.CharField(choices=[("simulated", "Simulato / sviluppo"), ("paypal", "PayPal Business")], default="simulated", max_length=20)),
                ("environment", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(choices=[("created", "Creato"), ("pending", "In attesa"), ("succeeded", "Riuscito"), ("failed", "Fallito"), ("cancelled", "Annullato")], default="created", max_length=20)),
                ("external_order_id", models.CharField(blank=True, max_length=120)),
                ("external_transaction_id", models.CharField(blank=True, max_length=120)),
                ("admin_notes", models.TextField(blank=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="catalog.custombuildrequest")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="custom_build_payments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Pagamento build personalizzata",
                "verbose_name_plural": "Pagamenti build personalizzate",
                "ordering": ["-initiated_at"],
            },
        ),
    ]
