# Generated by Django 5.2.12 on 2026-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_custombuildpayment_custom_request_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuildpayment',
            name='checkout_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('mastercard', 'Mastercard'), ('visa', 'Visa'), ('amex', 'American Express')], default='paypal', max_length=20),
        ),
    ]
