# Generated by Django 5.2.12 on 2026-04-20 19:38

import django.db.models.deletion
from django.db import migrations, models


def move_catalog_purchase_requests_into_custom_flow(apps, schema_editor):
    BuildPurchaseRequest = apps.get_model("catalog", "BuildPurchaseRequest")
    CustomBuildRequest = apps.get_model("catalog", "CustomBuildRequest")

    status_map = {
        "new": "in_approval",
        "in_progress": "in_approval",
        "ready": "approved",
        "closed": "cancelled",
    }

    for purchase_request in BuildPurchaseRequest.objects.filter(custom_request__isnull=True, user__isnull=False).select_related("build", "user"):
        build = purchase_request.build
        customer_message = (purchase_request.message or "").strip() or "Nessuna nota aggiuntiva."
        custom_request = CustomBuildRequest.objects.create(
            user=purchase_request.user,
            request_origin="catalog_build",
            requested_build=build,
            budget_max=getattr(build, "price", None),
            currency="EUR",
            notes=f"Richiesta inviata dalla build {build.name}.\n\nMessaggio cliente:\n{customer_message}",
            status=status_map.get(purchase_request.status, "in_approval"),
        )
        purchase_request.custom_request = custom_request
        purchase_request.save(update_fields=["custom_request"])


def reverse_catalog_purchase_request_link(apps, schema_editor):
    BuildPurchaseRequest = apps.get_model("catalog", "BuildPurchaseRequest")
    CustomBuildRequest = apps.get_model("catalog", "CustomBuildRequest")

    linked_request_ids = list(
        BuildPurchaseRequest.objects.filter(custom_request__isnull=False).values_list("custom_request_id", flat=True)
    )
    BuildPurchaseRequest.objects.exclude(custom_request__isnull=True).update(custom_request=None)
    if linked_request_ids:
        CustomBuildRequest.objects.filter(pk__in=linked_request_ids, request_origin="catalog_build").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_custombuildpayment_checkout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildpurchaserequest',
            name='custom_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_purchase_request', to='catalog.custombuildrequest'),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='request_origin',
            field=models.CharField(choices=[('custom', 'Richiesta personalizzata'), ('catalog_build', 'Build del catalogo')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='requested_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_custom_requests', to='catalog.build'),
        ),
        migrations.AlterField(
            model_name='custombuildrequest',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(move_catalog_purchase_requests_into_custom_flow, reverse_catalog_purchase_request_link),
    ]
