# Generated by Django 5.2.12 on 2026-05-27 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_buildpurchaserequest_custom_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='ram_gb',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(128)], verbose_name='RAM installata (GB)'),
        ),
        migrations.AddField(
            model_name='build',
            name='vram_gb',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(64)], verbose_name='VRAM scheda video (GB)'),
        ),
    ]
