# Generated by Django 5.2.12 on 2026-05-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_build_ram_gb_build_vram_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='cpu_brand',
            field=models.CharField(choices=[('intel', 'Intel'), ('amd', 'AMD')], default='intel', max_length=20, verbose_name='Marca processore'),
        ),
        migrations.AddField(
            model_name='build',
            name='gpu_brand',
            field=models.CharField(choices=[('nvidia', 'NVIDIA'), ('radeon', 'Radeon AMD')], default='nvidia', max_length=20, verbose_name='Marca scheda video'),
        ),
        migrations.AddField(
            model_name='build',
            name='main_brand',
            field=models.CharField(choices=[('nvidia', 'NVIDIA'), ('radeon_amd', 'Radeon AMD'), ('intel', 'Intel'), ('amd', 'AMD'), ('asus', 'ASUS'), ('msi', 'MSI'), ('corsair', 'Corsair'), ('kingston', 'Kingston'), ('samsung', 'Samsung'), ('crucial', 'Crucial'), ('lian_li', 'Lian Li'), ('nzxt', 'NZXT')], default='nvidia', max_length=30, verbose_name='Marca principale'),
        ),
    ]
