# Generated by Codex on 2026-05-27

from django.db import migrations, models


VALID_CASE_BRANDS = {
    "corsair",
    "nzxt",
    "lian_li",
    "fractal_design",
    "cooler_master",
    "phanteks",
    "be_quiet",
    "hyte",
    "thermaltake",
    "deepcool",
    "asus",
    "msi",
    "antec",
    "montech",
    "silverstone",
}


def normalize_case_brand(apps, schema_editor):
    Build = apps.get_model("catalog", "Build")
    Build.objects.exclude(case_brand__in=VALID_CASE_BRANDS).update(case_brand="corsair")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_build_cpu_brand_build_gpu_brand_build_main_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="build",
            old_name="main_brand",
            new_name="case_brand",
        ),
        migrations.AlterField(
            model_name="build",
            name="case_brand",
            field=models.CharField(
                choices=[
                    ("corsair", "Corsair"),
                    ("nzxt", "NZXT"),
                    ("lian_li", "Lian Li"),
                    ("fractal_design", "Fractal Design"),
                    ("cooler_master", "Cooler Master"),
                    ("phanteks", "Phanteks"),
                    ("be_quiet", "be quiet!"),
                    ("hyte", "HYTE"),
                    ("thermaltake", "Thermaltake"),
                    ("deepcool", "DeepCool"),
                    ("asus", "ASUS"),
                    ("msi", "MSI"),
                    ("antec", "Antec"),
                    ("montech", "Montech"),
                    ("silverstone", "SilverStone"),
                ],
                default="corsair",
                max_length=30,
                verbose_name="Marca case",
            ),
        ),
        migrations.RunPython(normalize_case_brand, migrations.RunPython.noop),
    ]
