# Generated by Django 5.2.12 on 2026-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_main_brand_case_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='gpu_brand',
            field=models.CharField(choices=[('integrated', 'Integrata (predefinita)'), ('nvidia', 'NVIDIA'), ('radeon', 'Radeon AMD'), ('intel_arc', 'Intel Arc')], default='integrated', max_length=20, verbose_name='Marca scheda video'),
        ),
    ]
