# Generated by Django 5.2.12 on 2026-05-27 14:56

from django.db import migrations, models


def initialize_sold_counts(apps, schema_editor):
    Build = apps.get_model("catalog", "Build")
    CustomBuildRequest = apps.get_model("catalog", "CustomBuildRequest")

    for build in Build.objects.all():
        sold_count = CustomBuildRequest.objects.filter(
            requested_build_id=build.pk,
            status="paid",
        ).count()
        if sold_count:
            build.sold_count = sold_count
            build.save(update_fields=["sold_count"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_build_gpu_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Vendite registrate'),
        ),
        migrations.RunPython(initialize_sold_counts, migrations.RunPython.noop),
    ]
