# Generated by Django 5.2.12 on 2026-05-27 16:54

import django.utils.timezone
from django.db import migrations, models


def initialize_release_dates(apps, schema_editor):
    Build = apps.get_model("catalog", "Build")
    for build in Build.objects.all():
        build.release_date = django.utils.timezone.localtime(build.created_at).date()
        build.save(update_fields=["release_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_build_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data uscita'),
        ),
        migrations.RunPython(initialize_release_dates, migrations.RunPython.noop),
    ]
